# Generated by Django 4.2.2 on 2023-06-19 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Major Name')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('percentage', models.FloatField(auto_created=True, editable=False)),
                ('student_id', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='Student ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('yearly_average', models.FloatField(verbose_name='Yearly Average')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.major')),
            ],
        ),
    ]
