# Generated by Django 4.1.7 on 2023-06-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=200, verbose_name='Card Number')),
                ('card_date', models.CharField(max_length=200, verbose_name='Expiration Date')),
                ('card_cvv', models.CharField(max_length=100, verbose_name='CVV')),
            ],
        ),
    ]
